<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-12-15 at 15:53:03.
 */
require '/../../metiers/FluxRSS.php';
class FluxRSSTest extends PHPUnit_Framework_TestCase {

    /**
     * @var FluxRSS
     */
    private $fluxRSS;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        $this->fluxRSS = new FluxRSS("0111fd38ac","https://news.google.com/news/feeds?pz=1&cf=all&ned=en&q=mortality+wild+boars&output=rss","unofficial");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

     /**
     * @covers FluxRSS::__construct($id, $url, $reliability)
     * @todo   Implement test__construct().
     */
    public function test__construct() {
        $fluxRSS = new FluxRSS("0111fdhjui","https://news.google.com/news/feeds?pz=1&cf=all&ned=en&q=mortality+wild+horse&output=rss","unofficial");    
        $this->assertEquals($fluxRSS->getId(),"0111fdhjui");
    }
    
    /**
     * @covers FluxRSS::getId
     * @todo   Implement testGetId().
     */
    public function testGetId() {
        $this->assertEquals($this->fluxRSS->getId(),"0111fd38ac");
    }

    /**
     * @covers FluxRSS::getUrl
     * @todo   Implement testGetUrl().
     */
    public function testGetUrl() {
        $this->assertEquals($this->fluxRSS->getUrl(),"https://news.google.com/news/feeds?pz=1&cf=all&ned=en&q=mortality+wild+boars&output=rss");
    }

    /**
     * @covers FluxRSS::getReliability
     * @todo   Implement testGetReliability().
     */
    public function testGetReliability() {
        $this->assertEquals($this->fluxRSS->getReliability(),"unofficial");
    }

}
