<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-12-15 at 15:40:28.
 */
require '/../../metiers/Hote.php';
class HoteTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Hote
     */
    private $hote;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        $this->hote = new Hote("pigs");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown() {
        
    }

        /**
     * @covers Hote::__construct($mot_clef)
     * @todo   Implement test__construct().
     */
    public function test__construct() {
        $hote = new Hote("horse");
        $this->assertEquals($hote->getMot_clef(),"horse");
    }
    
    
    /**
     * @covers Hote::getMot_clef
     * @todo   Implement testGetMot_clef().
     */
    public function testGetMot_clef() {
        $this->assertEquals($this->hote->getMot_clef(),"pigs");
    }

}
