<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-12-16 at 14:10:03.
 */
require '/../../verification/Parametre.php';
class ParametreTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Parameter
     */
    private $parametre;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->parametre = new Parameter();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Parametre::getParam
     * @todo   Implement testGetParam().
     */
    public function testGetParam() {
        //variable param n'existe pas
        $this->assertNull($this->parametre->getParam("param"),"parameter not known");
    }

}
