language: php

php:
  - 5.3

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit

matrix:
  include:
    - php: 5.3
      dist: precise
  fast_finish: true
  
branches:
    only:
        - master
        - tests
        
notifications:
    on_success: never
    on_failure: always
