<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-12-13 at 20:52:09.
 */
class UserTest extends PHPUnit_Framework_TestCase {

    /**
     * @var User
     */
    protected $user;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->user = new User("gerard", "dubois", "gerarddubois@gmail.com", "bidon", "user", 0);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers User::getFirstname
     * @todo   Implement testGetFirstname().
     */
    public function testGetFirstname() {
        $this->assertEquals("gerard",  $this->user->getFirstname());
    }

    /**
     * @covers User::getLastName
     * @todo   Implement testGetLastName().
     */
    public function testGetLastName() {
        $this->assertEquals("dubois",  $this->user->getLastName());
    }

    /**
     * @covers User::getEmail
     * @todo   Implement testGetEmail().
     */
    public function testGetEmail() {
        $this->assertEquals("gerarddubois@gmail.com",  $this->user->getEmail());
    }

    /**
     * @covers User::getPassword
     * @todo   Implement testGetPassword().
     */
    public function testGetPassword() {
        $this->assertEquals("bidon",  $this->user->getPassword());
    }

    /**
     * @covers User::getRole
     * @todo   Implement testGetRole().
     */
    public function testGetRole() {
        $this->assertEquals("user",  $this->user->getRole());
    }

    /**
     * @covers User::getOnline
     * @todo   Implement testGetOnline().
     */
    public function testGetOnline() {
        $this->assertEquals(0,  $this->user->getOnline());
    }

    /**
     * @covers User::expose
     * @todo   Implement testExpose().
     */
    public function testExpose() {
        $this->assertInternalType('array', $this->user->expose());
    }

}
