<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-12-12 at 09:03:15.
 */
require './persistence/DAL.php';
require './business/Conference.php';
require './business/User.php';

class DALTest extends PHPUnit_Framework_TestCase {

    /**
     * @var DAL
     */
    protected $dal;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->dal = new DAL;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers DAL::get_user
     * @todo   Implement testGet_user().
     */
    public function testGet_user() {
        $email="stephanevalente@gmail.com";
        $userInfo = $this->dal->get_user($email, "./test/persistence/DB/user.json");
        $this->assertInternalType('array',$userInfo);
        $this->assertEquals('Stephane', $userInfo['firstname']);
        $this->assertEquals('Valente', $userInfo['lastname']);
        $this->assertEquals('stephanevalente@gmail.com', $userInfo['email']);
        $this->assertEquals('admin', $userInfo['role']);
        $this->assertEquals(0, $userInfo['online']);
    }

    /**
     * @covers DAL::get_future_conferences
     * @todo   Implement testGet_future_conferences().
     */
    public function testGet_future_conferences() {
       $conferencesInfo = $this->dal->get_future_conferences("./test/persistence/DB/conference.json");
       foreach ($conferencesInfo as $key => $conferenceInfo) {
           $this->assertGreaterThan(time(), $conferenceInfo['date']);
           $this->assertArrayHasKey('id', $conferenceInfo);
           $this->assertArrayHasKey('title', $conferenceInfo);
           $this->assertArrayHasKey('description', $conferenceInfo);
           $this->assertArrayHasKey('address', $conferenceInfo);
           $this->assertArrayHasKey('speaker', $conferenceInfo);
       }
    }

    /**
     * @covers DAL::get_conferences
     * @todo   Implement testGet_conferences().
     */
    public function testGet_conferences() {
        $conferencesInfo = $this->dal->get_conferences("./test/persistence/DB/conference.json");
        $this->assertEquals(5, count($conferencesInfo));
        foreach ($conferencesInfo as $key => $conferenceInfo) {
           $this->assertArrayHasKey('id', $conferenceInfo);
           $this->assertArrayHasKey('date', $conferenceInfo);
           $this->assertArrayHasKey('title', $conferenceInfo);
           $this->assertArrayHasKey('description', $conferenceInfo);
           $this->assertArrayHasKey('address', $conferenceInfo);
           $this->assertArrayHasKey('speaker', $conferenceInfo);
       }
    }

    /**
     * @covers DAL::save_conferences
     * @todo   Implement testSave_conferences().
     */
    public function testSave_conferences() {
        $conferencesInfo = $this->dal->get_conferences("./test/persistence/DB/conference.json");
        $newConference = new Conference("1", "1513069717", "conference test", "description test", "address test", "speaker test");
        $tabConf[$newConference->getId()]=$newConference->expose();
        $this->dal->save_conferences($tabConf,"./test/persistence/DB/conference.json");
        $conferenceInfo = $this->dal->get_conferences("./test/persistence/DB/conference.json");
        $this->assertEquals('1513069717', $conferenceInfo[$newConference->getId()]['date']);
        $this->assertEquals('conference test', $conferenceInfo[$newConference->getId()]['title']);
        $this->assertEquals('description test', $conferenceInfo[$newConference->getId()]['description']);
        $this->assertEquals('address test', $conferenceInfo[$newConference->getId()]['address']);
        $this->assertEquals('speaker test', $conferenceInfo[$newConference->getId()]['speaker']);
        $this->dal->save_conferences($conferencesInfo, "./test/persistence/DB/conference.json");
    }

    /**
     * @covers DAL::save_state_user
     * @todo   Implement testSave_state_user().
     */
    public function testSave_state_user() {
        $userOrigin = new User("Stephane", "Valente", "stephanevalente@gmail.com", "f33227a7e80a9709f6998f542bb0ce6b", "admin", "0");
        $user = new User("Stephane", "Valente", "stephanevalente@gmail.com", "1234", "user", "1");
        
        $this->dal->save_state_user($user, "./test/persistence/DB/user.json"); 
        
        $userInfo = $this->dal->get_user("stephanevalente@gmail.com", "./test/persistence/DB/user.json");
        $this->assertInternalType('array',$userInfo);
        $this->assertEquals('Stephane', $userInfo['firstname']);
        $this->assertEquals('Valente', $userInfo['lastname']);
        $this->assertEquals('stephanevalente@gmail.com', $userInfo['email']);
        $this->assertEquals(1, $userInfo['online']);
        $this->assertEquals('user', $userInfo['role']);
        
        $this->dal->save_state_user($userOrigin, "./test/persistence/DB/user.json");
    }

    /**
     * @covers DAL::isLike
     * @todo   Implement testIsLike().
     */
    public function testIsLike() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DAL::getNbLikeOfConference
     * @todo   Implement testGetNbLikeOfConference().
     */
    public function testGetNbLikeOfConference() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DAL::getLikes
     * @todo   Implement testGetLikes().
     */
    public function testGetLikes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DAL::saveLikes
     * @todo   Implement testSaveLikes().
     */
    public function testSaveLikes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
